// Generated by scripts/nmos/generate-ms0502.py from the AMWA models. Do not edit.
//
//   AMWA-TV/ms-05-02 at 0f4c7d1 2026-09-18
//   AMWA-TV/nmos-control-feature-sets at d6981c3 2026-09-25
//
// The models are Copyright AMWA and licensed under the Apache License, Version 2.0.

// swiftformat:disable all

extension NcStandardModel {
  static let frameworkClasses: [NcClassDescriptor] = [
    .init(
      description: "NcObject class descriptor",
      classID: [1], name: "NcObject", fixedRole: nil,
      properties: [
        .init(description: "Static value. All instances of the same class will have the same identity value", id: .init(level: 1, index: 1), name: "classId", typeName: "NcClassId", isReadOnly: true),
        .init(description: "Object identifier", id: .init(level: 1, index: 2), name: "oid", typeName: "NcOid", isReadOnly: true),
        .init(description: "TRUE iff OID is hardwired into device", id: .init(level: 1, index: 3), name: "constantOid", typeName: "NcBoolean", isReadOnly: true),
        .init(description: "OID of containing block. Can only ever be null for the root block", id: .init(level: 1, index: 4), name: "owner", typeName: "NcOid", isReadOnly: true, isNullable: true),
        .init(description: "Role of object in the containing block", id: .init(level: 1, index: 5), name: "role", typeName: "NcString", isReadOnly: true),
        .init(description: "Scribble strip", id: .init(level: 1, index: 6), name: "userLabel", typeName: "NcString", isReadOnly: false, isNullable: true),
        .init(description: "Touchpoints to other contexts", id: .init(level: 1, index: 7), name: "touchpoints", typeName: "NcTouchpoint", isReadOnly: true, isNullable: true, isSequence: true),
        .init(description: "Runtime property constraints", id: .init(level: 1, index: 8), name: "runtimePropertyConstraints", typeName: "NcPropertyConstraints", isReadOnly: true, isNullable: true, isSequence: true),
      ],
      methods: [
        .init(description: "Get property value", id: .init(level: 1, index: 1), name: "Get", resultDatatype: "NcMethodResultPropertyValue", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
        ]),
        .init(description: "Set property value", id: .init(level: 1, index: 2), name: "Set", resultDatatype: "NcMethodResult", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
          .init(description: "Property value", name: "value", typeName: nil, isNullable: true),
        ]),
        .init(description: "Get sequence item", id: .init(level: 1, index: 3), name: "GetSequenceItem", resultDatatype: "NcMethodResultPropertyValue", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
          .init(description: "Index of item in the sequence", name: "index", typeName: "NcId"),
        ]),
        .init(description: "Set sequence item value", id: .init(level: 1, index: 4), name: "SetSequenceItem", resultDatatype: "NcMethodResult", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
          .init(description: "Index of item in the sequence", name: "index", typeName: "NcId"),
          .init(description: "Value", name: "value", typeName: nil, isNullable: true),
        ]),
        .init(description: "Add item to sequence", id: .init(level: 1, index: 5), name: "AddSequenceItem", resultDatatype: "NcMethodResultId", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
          .init(description: "Value", name: "value", typeName: nil, isNullable: true),
        ]),
        .init(description: "Delete sequence item", id: .init(level: 1, index: 6), name: "RemoveSequenceItem", resultDatatype: "NcMethodResult", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
          .init(description: "Index of item in the sequence", name: "index", typeName: "NcId"),
        ]),
        .init(description: "Get sequence length", id: .init(level: 1, index: 7), name: "GetSequenceLength", resultDatatype: "NcMethodResultLength", parameters: [
          .init(description: "Property id", name: "id", typeName: "NcPropertyId"),
        ]),
      ],
      events: [
        .init(description: "Property changed event", id: .init(level: 1, index: 1), name: "PropertyChanged", eventDatatype: "NcPropertyChangedEventData"),
      ]
    ),
    .init(
      description: "NcBlock class descriptor",
      classID: [1, 1], name: "NcBlock", fixedRole: nil,
      properties: [
        .init(description: "TRUE if block is functional", id: .init(level: 2, index: 1), name: "enabled", typeName: "NcBoolean", isReadOnly: true),
        .init(description: "Descriptors of this block's members", id: .init(level: 2, index: 2), name: "members", typeName: "NcBlockMemberDescriptor", isReadOnly: true, isSequence: true),
      ],
      methods: [
        .init(description: "Gets descriptors of members of the block", id: .init(level: 2, index: 1), name: "GetMemberDescriptors", resultDatatype: "NcMethodResultBlockMemberDescriptors", parameters: [
          .init(description: "If recurse is set to true, nested members can be retrieved", name: "recurse", typeName: "NcBoolean"),
        ]),
        .init(description: "Finds member(s) by path", id: .init(level: 2, index: 2), name: "FindMembersByPath", resultDatatype: "NcMethodResultBlockMemberDescriptors", parameters: [
          .init(description: "Relative path to search for (MUST not include the role of the block targeted by oid)", name: "path", typeName: "NcRolePath"),
        ]),
        .init(description: "Finds members with given role name or fragment", id: .init(level: 2, index: 3), name: "FindMembersByRole", resultDatatype: "NcMethodResultBlockMemberDescriptors", parameters: [
          .init(description: "Role text to search for", name: "role", typeName: "NcString"),
          .init(description: "Signals if the comparison should be case sensitive", name: "caseSensitive", typeName: "NcBoolean"),
          .init(description: "TRUE to only return exact matches", name: "matchWholeString", typeName: "NcBoolean"),
          .init(description: "TRUE to search nested blocks", name: "recurse", typeName: "NcBoolean"),
        ]),
        .init(description: "Finds members with given class id", id: .init(level: 2, index: 4), name: "FindMembersByClassId", resultDatatype: "NcMethodResultBlockMemberDescriptors", parameters: [
          .init(description: "Class id to search for", name: "classId", typeName: "NcClassId"),
          .init(description: "If TRUE it will also include derived class descriptors", name: "includeDerived", typeName: "NcBoolean"),
          .init(description: "TRUE to search nested blocks", name: "recurse", typeName: "NcBoolean"),
        ]),
      ],
      events: [
      ]
    ),
    .init(
      description: "NcWorker class descriptor",
      classID: [1, 2], name: "NcWorker", fixedRole: nil,
      properties: [
        .init(description: "TRUE iff worker is enabled", id: .init(level: 2, index: 1), name: "enabled", typeName: "NcBoolean", isReadOnly: false),
      ],
      methods: [
      ],
      events: [
      ]
    ),
    .init(
      description: "NcManager class descriptor",
      classID: [1, 3], name: "NcManager", fixedRole: nil,
      properties: [
      ],
      methods: [
      ],
      events: [
      ]
    ),
    .init(
      description: "NcDeviceManager class descriptor",
      classID: [1, 3, 1], name: "NcDeviceManager", fixedRole: "DeviceManager",
      properties: [
        .init(description: "Version of MS-05-02 that this device uses", id: .init(level: 3, index: 1), name: "ncVersion", typeName: "NcVersionCode", isReadOnly: true),
        .init(description: "Manufacturer descriptor", id: .init(level: 3, index: 2), name: "manufacturer", typeName: "NcManufacturer", isReadOnly: true),
        .init(description: "Product descriptor", id: .init(level: 3, index: 3), name: "product", typeName: "NcProduct", isReadOnly: true),
        .init(description: "Serial number", id: .init(level: 3, index: 4), name: "serialNumber", typeName: "NcString", isReadOnly: true),
        .init(description: "Asset tracking identifier (user specified)", id: .init(level: 3, index: 5), name: "userInventoryCode", typeName: "NcString", isReadOnly: false, isNullable: true),
        .init(description: "Name of this device in the application. Instance name, not product name.", id: .init(level: 3, index: 6), name: "deviceName", typeName: "NcString", isReadOnly: false, isNullable: true),
        .init(description: "Role of this device in the application.", id: .init(level: 3, index: 7), name: "deviceRole", typeName: "NcString", isReadOnly: false, isNullable: true),
        .init(description: "Device operational state", id: .init(level: 3, index: 8), name: "operationalState", typeName: "NcDeviceOperationalState", isReadOnly: true),
        .init(description: "Reason for most recent reset", id: .init(level: 3, index: 9), name: "resetCause", typeName: "NcResetCause", isReadOnly: true),
        .init(description: "Arbitrary message from dev to controller", id: .init(level: 3, index: 10), name: "message", typeName: "NcString", isReadOnly: true, isNullable: true),
      ],
      methods: [
      ],
      events: [
      ]
    ),
    .init(
      description: "NcClassManager class descriptor",
      classID: [1, 3, 2], name: "NcClassManager", fixedRole: "ClassManager",
      properties: [
        .init(description: "Descriptions of all control classes in the device (descriptors do not contain inherited elements)", id: .init(level: 3, index: 1), name: "controlClasses", typeName: "NcClassDescriptor", isReadOnly: true, isSequence: true),
        .init(description: "Descriptions of all data types in the device (descriptors do not contain inherited elements)", id: .init(level: 3, index: 2), name: "datatypes", typeName: "NcDatatypeDescriptor", isReadOnly: true, isSequence: true),
      ],
      methods: [
        .init(description: "Get a single class descriptor", id: .init(level: 3, index: 1), name: "GetControlClass", resultDatatype: "NcMethodResultClassDescriptor", parameters: [
          .init(description: "class ID", name: "classId", typeName: "NcClassId"),
          .init(description: "If set the descriptor would contain all inherited elements", name: "includeInherited", typeName: "NcBoolean"),
        ]),
        .init(description: "Get a single datatype descriptor", id: .init(level: 3, index: 2), name: "GetDatatype", resultDatatype: "NcMethodResultDatatypeDescriptor", parameters: [
          .init(description: "name of datatype", name: "name", typeName: "NcName"),
          .init(description: "If set the descriptor would contain all inherited elements", name: "includeInherited", typeName: "NcBoolean"),
        ]),
      ],
      events: [
      ]
    ),
  ]

  static let frameworkDatatypes: [NcDatatypeDescriptor] = [
    .init(description: nil, name: "NcBoolean", kind: .primitive),
    .init(description: nil, name: "NcInt16", kind: .primitive),
    .init(description: nil, name: "NcInt32", kind: .primitive),
    .init(description: nil, name: "NcInt64", kind: .primitive),
    .init(description: nil, name: "NcUint16", kind: .primitive),
    .init(description: nil, name: "NcUint32", kind: .primitive),
    .init(description: nil, name: "NcUint64", kind: .primitive),
    .init(description: nil, name: "NcFloat32", kind: .primitive),
    .init(description: nil, name: "NcFloat64", kind: .primitive),
    .init(description: nil, name: "NcString", kind: .primitive),
    .init(description: "Descriptor which is specific to a block member", name: "NcBlockMemberDescriptor", kind: .struct(fields: [
      .init(description: "Role of member in its containing block", name: "role", typeName: "NcString"),
      .init(description: "OID of member", name: "oid", typeName: "NcOid"),
      .init(description: "TRUE iff member's OID is hardwired into device", name: "constantOid", typeName: "NcBoolean"),
      .init(description: "Class ID", name: "classId", typeName: "NcClassId"),
      .init(description: "User label", name: "userLabel", typeName: "NcString", isNullable: true),
      .init(description: "Containing block's OID", name: "owner", typeName: "NcOid"),
    ], parentType: "NcDescriptor")),
    .init(description: "Descriptor of a class", name: "NcClassDescriptor", kind: .struct(fields: [
      .init(description: "Identity of the class", name: "classId", typeName: "NcClassId"),
      .init(description: "Name of the class", name: "name", typeName: "NcName"),
      .init(description: "Role if the class has fixed role (manager classes)", name: "fixedRole", typeName: "NcString", isNullable: true),
      .init(description: "Property descriptors", name: "properties", typeName: "NcPropertyDescriptor", isSequence: true),
      .init(description: "Method descriptors", name: "methods", typeName: "NcMethodDescriptor", isSequence: true),
      .init(description: "Event descriptors", name: "events", typeName: "NcEventDescriptor", isSequence: true),
    ], parentType: "NcDescriptor")),
    .init(description: "Sequence of class ID fields.", name: "NcClassId", kind: .typedef(parentType: "NcInt32", isSequence: true)),
    .init(description: "Base datatype descriptor", name: "NcDatatypeDescriptor", kind: .struct(fields: [
      .init(description: "Datatype name", name: "name", typeName: "NcName"),
      .init(description: "Type: Primitive, Typedef, Struct, Enum", name: "type", typeName: "NcDatatypeType"),
      .init(description: "Optional constraints on top of the underlying data type", name: "constraints", typeName: "NcParameterConstraints", isNullable: true),
    ], parentType: "NcDescriptor")),
    .init(description: "Enum datatype descriptor", name: "NcDatatypeDescriptorEnum", kind: .struct(fields: [
      .init(description: "One item descriptor per enum option", name: "items", typeName: "NcEnumItemDescriptor", isSequence: true),
    ], parentType: "NcDatatypeDescriptor")),
    .init(description: "Primitive datatype descriptor", name: "NcDatatypeDescriptorPrimitive", kind: .struct(fields: [
    ], parentType: "NcDatatypeDescriptor")),
    .init(description: "Struct datatype descriptor", name: "NcDatatypeDescriptorStruct", kind: .struct(fields: [
      .init(description: "One item descriptor per field of the struct", name: "fields", typeName: "NcFieldDescriptor", isSequence: true),
      .init(description: "Name of the parent type if any or null if it has no parent", name: "parentType", typeName: "NcName", isNullable: true),
    ], parentType: "NcDatatypeDescriptor")),
    .init(description: "Type def datatype descriptor", name: "NcDatatypeDescriptorTypeDef", kind: .struct(fields: [
      .init(description: "Original typedef datatype name", name: "parentType", typeName: "NcName"),
      .init(description: "TRUE iff type is a typedef sequence of another type", name: "isSequence", typeName: "NcBoolean"),
    ], parentType: "NcDatatypeDescriptor")),
    .init(description: "Datatype type", name: "NcDatatypeType", kind: .enum(items: [
      .init(description: "Primitive datatype", name: "Primitive", value: 0),
      .init(description: "Simple alias of another datatype", name: "Typedef", value: 1),
      .init(description: "Data structure", name: "Struct", value: 2),
      .init(description: "Enum datatype", name: "Enum", value: 3),
    ])),
    .init(description: "Base descriptor", name: "NcDescriptor", kind: .struct(fields: [
      .init(description: "Optional user facing description", name: "description", typeName: "NcString", isNullable: true),
    ], parentType: nil)),
    .init(description: "Device generic operational state", name: "NcDeviceGenericState", kind: .enum(items: [
      .init(description: "Unknown", name: "Unknown", value: 0),
      .init(description: "Normal operation", name: "NormalOperation", value: 1),
      .init(description: "Device is initializing", name: "Initializing", value: 2),
      .init(description: "Device is performing a software or firmware update", name: "Updating", value: 3),
      .init(description: "Device is experiencing a licensing error", name: "LicensingError", value: 4),
      .init(description: "Device is experiencing an internal error", name: "InternalError", value: 5),
    ])),
    .init(description: "Device operational state", name: "NcDeviceOperationalState", kind: .struct(fields: [
      .init(description: "Generic operational state", name: "generic", typeName: "NcDeviceGenericState"),
      .init(description: "Specific device details", name: "deviceSpecificDetails", typeName: "NcString", isNullable: true),
    ], parentType: nil)),
    .init(description: "Class element id which contains the level and index", name: "NcElementId", kind: .struct(fields: [
      .init(description: "Level of the element", name: "level", typeName: "NcUint16"),
      .init(description: "Index of the element", name: "index", typeName: "NcUint16"),
    ], parentType: nil)),
    .init(description: "Descriptor of an enum item", name: "NcEnumItemDescriptor", kind: .struct(fields: [
      .init(description: "Name of option", name: "name", typeName: "NcName"),
      .init(description: "Enum item numerical value", name: "value", typeName: "NcUint16"),
    ], parentType: "NcDescriptor")),
    .init(description: "Descriptor of a class event", name: "NcEventDescriptor", kind: .struct(fields: [
      .init(description: "Event id with level and index", name: "id", typeName: "NcEventId"),
      .init(description: "Name of event", name: "name", typeName: "NcName"),
      .init(description: "Name of event data's datatype", name: "eventDatatype", typeName: "NcName"),
      .init(description: "TRUE iff property is marked as deprecated", name: "isDeprecated", typeName: "NcBoolean"),
    ], parentType: "NcDescriptor")),
    .init(description: "Event id which contains the level and index", name: "NcEventId", kind: .struct(fields: [
    ], parentType: "NcElementId")),
    .init(description: "Descriptor of a field of a struct", name: "NcFieldDescriptor", kind: .struct(fields: [
      .init(description: "Name of field", name: "name", typeName: "NcName"),
      .init(description: "Name of field's datatype. Can only ever be null if the type is any", name: "typeName", typeName: "NcName", isNullable: true),
      .init(description: "TRUE iff field is nullable", name: "isNullable", typeName: "NcBoolean"),
      .init(description: "TRUE iff field is a sequence", name: "isSequence", typeName: "NcBoolean"),
      .init(description: "Optional constraints on top of the underlying data type", name: "constraints", typeName: "NcParameterConstraints", isNullable: true),
    ], parentType: "NcDescriptor")),
    .init(description: "Identity handler", name: "NcId", kind: .typedef(parentType: "NcUint32", isSequence: false)),
    .init(description: "Manufacturer descriptor", name: "NcManufacturer", kind: .struct(fields: [
      .init(description: "Manufacturer's name", name: "name", typeName: "NcString"),
      .init(description: "IEEE OUI or CID of manufacturer", name: "organizationId", typeName: "NcOrganizationId", isNullable: true),
      .init(description: "URL of the manufacturer's website", name: "website", typeName: "NcUri", isNullable: true),
    ], parentType: nil)),
    .init(description: "Descriptor of a class method", name: "NcMethodDescriptor", kind: .struct(fields: [
      .init(description: "Method id with level and index", name: "id", typeName: "NcMethodId"),
      .init(description: "Name of method", name: "name", typeName: "NcName"),
      .init(description: "Name of method result's datatype", name: "resultDatatype", typeName: "NcName"),
      .init(description: "Parameter descriptors if any", name: "parameters", typeName: "NcParameterDescriptor", isSequence: true),
      .init(description: "TRUE iff property is marked as deprecated", name: "isDeprecated", typeName: "NcBoolean"),
    ], parentType: "NcDescriptor")),
    .init(description: "Method id which contains the level and index", name: "NcMethodId", kind: .struct(fields: [
    ], parentType: "NcElementId")),
    .init(description: "Base result of the invoked method", name: "NcMethodResult", kind: .struct(fields: [
      .init(description: "Status for the invoked method", name: "status", typeName: "NcMethodStatus"),
    ], parentType: nil)),
    .init(description: "Method result containing block member descriptors as the value", name: "NcMethodResultBlockMemberDescriptors", kind: .struct(fields: [
      .init(description: "Block member descriptors method result value", name: "value", typeName: "NcBlockMemberDescriptor", isSequence: true),
    ], parentType: "NcMethodResult")),
    .init(description: "Method result containing a class descriptor as the value", name: "NcMethodResultClassDescriptor", kind: .struct(fields: [
      .init(description: "Class descriptor method result value", name: "value", typeName: "NcClassDescriptor"),
    ], parentType: "NcMethodResult")),
    .init(description: "Method result containing a datatype descriptor as the value", name: "NcMethodResultDatatypeDescriptor", kind: .struct(fields: [
      .init(description: "Datatype descriptor method result value", name: "value", typeName: "NcDatatypeDescriptor"),
    ], parentType: "NcMethodResult")),
    .init(description: "Error result - to be used when the method call encounters an error", name: "NcMethodResultError", kind: .struct(fields: [
      .init(description: "Error message", name: "errorMessage", typeName: "NcString"),
    ], parentType: "NcMethodResult")),
    .init(description: "Id method result", name: "NcMethodResultId", kind: .struct(fields: [
      .init(description: "Id result value", name: "value", typeName: "NcId"),
    ], parentType: "NcMethodResult")),
    .init(description: "Length method result", name: "NcMethodResultLength", kind: .struct(fields: [
      .init(description: "Sequence length result value. MUST be null if the sequence is null", name: "value", typeName: "NcUint32", isNullable: true),
    ], parentType: "NcMethodResult")),
    .init(description: "Result when invoking the getter method associated with a property", name: "NcMethodResultPropertyValue", kind: .struct(fields: [
      .init(description: "Getter method value for the associated property", name: "value", typeName: nil, isNullable: true),
    ], parentType: "NcMethodResult")),
    .init(description: "Method invokation status", name: "NcMethodStatus", kind: .enum(items: [
      .init(description: "Method call was successful", name: "Ok", value: 200),
      .init(description: "Method call was successful but targeted property is deprecated", name: "PropertyDeprecated", value: 298),
      .init(description: "Method call was successful but method is deprecated", name: "MethodDeprecated", value: 299),
      .init(description: "Badly-formed command (e.g. the incoming command has invalid message encoding and cannot be parsed by the underlying protocol)", name: "BadCommandFormat", value: 400),
      .init(description: "Client is not authorized", name: "Unauthorized", value: 401),
      .init(description: "Command addresses a nonexistent object", name: "BadOid", value: 404),
      .init(description: "Attempt to change read-only state", name: "Readonly", value: 405),
      .init(description: "Method call is invalid in current operating context (e.g. attempting to invoke a method when the object is disabled)", name: "InvalidRequest", value: 406),
      .init(description: "There is a conflict with the current state of the device", name: "Conflict", value: 409),
      .init(description: "Something was too big", name: "BufferOverflow", value: 413),
      .init(description: "Index is outside the available range", name: "IndexOutOfBounds", value: 414),
      .init(description: "Method parameter does not meet expectations (e.g. attempting to invoke a method with an invalid type for one of its parameters)", name: "ParameterError", value: 417),
      .init(description: "Addressed object is locked", name: "Locked", value: 423),
      .init(description: "Internal device error", name: "DeviceError", value: 500),
      .init(description: "Addressed method is not implemented by the addressed object", name: "MethodNotImplemented", value: 501),
      .init(description: "Addressed property is not implemented by the addressed object", name: "PropertyNotImplemented", value: 502),
      .init(description: "The device is not ready to handle any commands", name: "NotReady", value: 503),
      .init(description: "Method call did not finish within the allotted time", name: "Timeout", value: 504),
    ])),
    .init(description: "Programmatically significant name, alphanumerics + underscore, no spaces", name: "NcName", kind: .typedef(parentType: "NcString", isSequence: false)),
    .init(description: "Object id", name: "NcOid", kind: .typedef(parentType: "NcUint32", isSequence: false)),
    .init(description: "Unique 24-bit organization id", name: "NcOrganizationId", kind: .typedef(parentType: "NcInt32", isSequence: false)),
    .init(description: "Abstract parameter constraints class", name: "NcParameterConstraints", kind: .struct(fields: [
      .init(description: "Default value", name: "defaultValue", typeName: nil, isNullable: true),
    ], parentType: nil)),
    .init(description: "Number parameter constraints class", name: "NcParameterConstraintsNumber", kind: .struct(fields: [
      .init(description: "Optional maximum", name: "maximum", typeName: nil, isNullable: true),
      .init(description: "Optional minimum", name: "minimum", typeName: nil, isNullable: true),
      .init(description: "Optional step", name: "step", typeName: nil, isNullable: true),
    ], parentType: "NcParameterConstraints")),
    .init(description: "String parameter constraints class", name: "NcParameterConstraintsString", kind: .struct(fields: [
      .init(description: "Maximum characters allowed", name: "maxCharacters", typeName: "NcUint32", isNullable: true),
      .init(description: "Regex pattern", name: "pattern", typeName: "NcRegex", isNullable: true),
    ], parentType: "NcParameterConstraints")),
    .init(description: "Descriptor of a method parameter", name: "NcParameterDescriptor", kind: .struct(fields: [
      .init(description: "Name of parameter", name: "name", typeName: "NcName"),
      .init(description: "Name of parameter's datatype. Can only ever be null if the type is any", name: "typeName", typeName: "NcName", isNullable: true),
      .init(description: "TRUE iff property is nullable", name: "isNullable", typeName: "NcBoolean"),
      .init(description: "TRUE iff property is a sequence", name: "isSequence", typeName: "NcBoolean"),
      .init(description: "Optional constraints on top of the underlying data type", name: "constraints", typeName: "NcParameterConstraints", isNullable: true),
    ], parentType: "NcDescriptor")),
    .init(description: "Product descriptor", name: "NcProduct", kind: .struct(fields: [
      .init(description: "Product name", name: "name", typeName: "NcString"),
      .init(description: "Manufacturer's unique key to product - model number, SKU, etc", name: "key", typeName: "NcString"),
      .init(description: "Manufacturer's product revision level code", name: "revisionLevel", typeName: "NcString"),
      .init(description: "Brand name under which product is sold", name: "brandName", typeName: "NcString", isNullable: true),
      .init(description: "Unique UUID of product (not product instance)", name: "uuid", typeName: "NcUuid", isNullable: true),
      .init(description: "Text description of product", name: "description", typeName: "NcString", isNullable: true),
    ], parentType: nil)),
    .init(description: "Type of property change", name: "NcPropertyChangeType", kind: .enum(items: [
      .init(description: "Current value changed", name: "ValueChanged", value: 0),
      .init(description: "Sequence item added", name: "SequenceItemAdded", value: 1),
      .init(description: "Sequence item changed", name: "SequenceItemChanged", value: 2),
      .init(description: "Sequence item removed", name: "SequenceItemRemoved", value: 3),
    ])),
    .init(description: "Payload of property-changed event", name: "NcPropertyChangedEventData", kind: .struct(fields: [
      .init(description: "The id of the property that changed", name: "propertyId", typeName: "NcPropertyId"),
      .init(description: "Information regarding the change type", name: "changeType", typeName: "NcPropertyChangeType"),
      .init(description: "Property-type specific value", name: "value", typeName: nil, isNullable: true),
      .init(description: "Index of sequence item if the property is a sequence", name: "sequenceItemIndex", typeName: "NcId", isNullable: true),
    ], parentType: nil)),
    .init(description: "Property constraints class", name: "NcPropertyConstraints", kind: .struct(fields: [
      .init(description: "The id of the property being constrained", name: "propertyId", typeName: "NcPropertyId"),
      .init(description: "Optional default value", name: "defaultValue", typeName: nil, isNullable: true),
    ], parentType: nil)),
    .init(description: "Number property constraints class", name: "NcPropertyConstraintsNumber", kind: .struct(fields: [
      .init(description: "Optional maximum", name: "maximum", typeName: nil, isNullable: true),
      .init(description: "Optional minimum", name: "minimum", typeName: nil, isNullable: true),
      .init(description: "Optional step", name: "step", typeName: nil, isNullable: true),
    ], parentType: "NcPropertyConstraints")),
    .init(description: "String property constraints class", name: "NcPropertyConstraintsString", kind: .struct(fields: [
      .init(description: "Maximum characters allowed", name: "maxCharacters", typeName: "NcUint32", isNullable: true),
      .init(description: "Regex pattern", name: "pattern", typeName: "NcRegex", isNullable: true),
    ], parentType: "NcPropertyConstraints")),
    .init(description: "Descriptor of a class property", name: "NcPropertyDescriptor", kind: .struct(fields: [
      .init(description: "Property id with level and index", name: "id", typeName: "NcPropertyId"),
      .init(description: "Name of property", name: "name", typeName: "NcName"),
      .init(description: "Name of property's datatype. Can only ever be null if the type is any", name: "typeName", typeName: "NcName", isNullable: true),
      .init(description: "TRUE iff property is read-only", name: "isReadOnly", typeName: "NcBoolean"),
      .init(description: "TRUE iff property is nullable", name: "isNullable", typeName: "NcBoolean"),
      .init(description: "TRUE iff property is a sequence", name: "isSequence", typeName: "NcBoolean"),
      .init(description: "TRUE iff property is marked as deprecated", name: "isDeprecated", typeName: "NcBoolean"),
      .init(description: "Optional constraints on top of the underlying data type", name: "constraints", typeName: "NcParameterConstraints", isNullable: true),
    ], parentType: "NcDescriptor")),
    .init(description: "Property id which contains the level and index", name: "NcPropertyId", kind: .struct(fields: [
    ], parentType: "NcElementId")),
    .init(description: "Regex pattern", name: "NcRegex", kind: .typedef(parentType: "NcString", isSequence: false)),
    .init(description: "Reset cause enum", name: "NcResetCause", kind: .enum(items: [
      .init(description: "Unknown", name: "Unknown", value: 0),
      .init(description: "Power on", name: "PowerOn", value: 1),
      .init(description: "Internal error", name: "InternalError", value: 2),
      .init(description: "Upgrade", name: "Upgrade", value: 3),
      .init(description: "Controller request", name: "ControllerRequest", value: 4),
      .init(description: "Manual request from the front panel", name: "ManualReset", value: 5),
    ])),
    .init(description: "Role path", name: "NcRolePath", kind: .typedef(parentType: "NcString", isSequence: true)),
    .init(description: "Time interval described in nanoseconds", name: "NcTimeInterval", kind: .typedef(parentType: "NcInt64", isSequence: false)),
    .init(description: "Base touchpoint class", name: "NcTouchpoint", kind: .struct(fields: [
      .init(description: "Context namespace", name: "contextNamespace", typeName: "NcString"),
    ], parentType: nil)),
    .init(description: "Touchpoint class for NMOS resources", name: "NcTouchpointNmos", kind: .struct(fields: [
      .init(description: "Context NMOS resource", name: "resource", typeName: "NcTouchpointResourceNmos"),
    ], parentType: "NcTouchpoint")),
    .init(description: "Touchpoint class for NMOS IS-08 resources", name: "NcTouchpointNmosChannelMapping", kind: .struct(fields: [
      .init(description: "Context Channel Mapping resource", name: "resource", typeName: "NcTouchpointResourceNmosChannelMapping"),
    ], parentType: "NcTouchpoint")),
    .init(description: "Touchpoint resource class", name: "NcTouchpointResource", kind: .struct(fields: [
      .init(description: "The type of the resource", name: "resourceType", typeName: "NcString"),
    ], parentType: nil)),
    .init(description: "Touchpoint resource class for NMOS resources", name: "NcTouchpointResourceNmos", kind: .struct(fields: [
      .init(description: "NMOS resource UUID", name: "id", typeName: "NcUuid"),
    ], parentType: "NcTouchpointResource")),
    .init(description: "Touchpoint resource class for NMOS resources", name: "NcTouchpointResourceNmosChannelMapping", kind: .struct(fields: [
      .init(description: "IS-08 Audio Channel Mapping input or output id", name: "ioId", typeName: "NcString"),
    ], parentType: "NcTouchpointResourceNmos")),
    .init(description: "Uniform resource identifier", name: "NcUri", kind: .typedef(parentType: "NcString", isSequence: false)),
    .init(description: "UUID", name: "NcUuid", kind: .typedef(parentType: "NcString", isSequence: false)),
    .init(description: "Version code in semantic versioning format", name: "NcVersionCode", kind: .typedef(parentType: "NcString", isSequence: false)),
  ]

  static let identificationClasses: [NcClassDescriptor] = [
    .init(
      description: "NcIdentBeacon class descriptor",
      classID: [1, 2, 1], name: "NcIdentBeacon", fixedRole: nil,
      properties: [
        .init(description: "Indicator active state", id: .init(level: 3, index: 1), name: "active", typeName: "NcBoolean", isReadOnly: false),
      ],
      methods: [
      ],
      events: [
      ]
    ),
  ]

  static let identificationDatatypes: [NcDatatypeDescriptor] = [
  ]

  static let monitoringClasses: [NcClassDescriptor] = [
    .init(
      description: "Baseline status monitoring class",
      classID: [1, 2, 2], name: "NcStatusMonitor", fixedRole: nil,
      properties: [
        .init(description: "Overall status property", id: .init(level: 3, index: 1), name: "overallStatus", typeName: "NcOverallStatus", isReadOnly: true),
        .init(description: "Overall status message property", id: .init(level: 3, index: 2), name: "overallStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Status reporting delay property (in seconds, default is 3s and 0 means no delay)", id: .init(level: 3, index: 3), name: "statusReportingDelay", typeName: "NcUint32", isReadOnly: false),
      ],
      methods: [
      ],
      events: [
      ]
    ),
    .init(
      description: "Receiver monitor class descriptor",
      classID: [1, 2, 2, 1], name: "NcReceiverMonitor", fixedRole: nil,
      properties: [
        .init(description: "Link status property", id: .init(level: 4, index: 1), name: "linkStatus", typeName: "NcLinkStatus", isReadOnly: true),
        .init(description: "Link status message property", id: .init(level: 4, index: 2), name: "linkStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Link status transition counter property", id: .init(level: 4, index: 3), name: "linkStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "Connection status property", id: .init(level: 4, index: 4), name: "connectionStatus", typeName: "NcConnectionStatus", isReadOnly: true),
        .init(description: "Connection status message property", id: .init(level: 4, index: 5), name: "connectionStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Connection status transition counter property", id: .init(level: 4, index: 6), name: "connectionStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "External synchronization status property", id: .init(level: 4, index: 7), name: "externalSynchronizationStatus", typeName: "NcSynchronizationStatus", isReadOnly: true),
        .init(description: "External synchronization status message property", id: .init(level: 4, index: 8), name: "externalSynchronizationStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "External synchronization status transition counter property", id: .init(level: 4, index: 9), name: "externalSynchronizationStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "Synchronization source id property", id: .init(level: 4, index: 10), name: "synchronizationSourceId", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Stream status property", id: .init(level: 4, index: 11), name: "streamStatus", typeName: "NcStreamStatus", isReadOnly: true),
        .init(description: "Stream status message property", id: .init(level: 4, index: 12), name: "streamStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Stream status transition counter property", id: .init(level: 4, index: 13), name: "streamStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "Automatic reset counters and status messages property (default: true)", id: .init(level: 4, index: 14), name: "autoResetCountersAndMessages", typeName: "NcBoolean", isReadOnly: false),
      ],
      methods: [
        .init(description: "Gets the lost packet counters", id: .init(level: 4, index: 1), name: "GetLostPacketCounters", resultDatatype: "NcMethodResultCounters", parameters: [
        ]),
        .init(description: "Gets the late packet counters", id: .init(level: 4, index: 2), name: "GetLatePacketCounters", resultDatatype: "NcMethodResultCounters", parameters: [
        ]),
        .init(description: "Resets ALL counters and status messages", id: .init(level: 4, index: 3), name: "ResetCountersAndMessages", resultDatatype: "NcMethodResult", parameters: [
        ]),
      ],
      events: [
      ]
    ),
    .init(
      description: "Sender monitor class descriptor",
      classID: [1, 2, 2, 2], name: "NcSenderMonitor", fixedRole: nil,
      properties: [
        .init(description: "Link status property", id: .init(level: 4, index: 1), name: "linkStatus", typeName: "NcLinkStatus", isReadOnly: true),
        .init(description: "Link status message property", id: .init(level: 4, index: 2), name: "linkStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Link status transition counter property", id: .init(level: 4, index: 3), name: "linkStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "Transmission status property", id: .init(level: 4, index: 4), name: "transmissionStatus", typeName: "NcTransmissionStatus", isReadOnly: true),
        .init(description: "Transmission status message property", id: .init(level: 4, index: 5), name: "transmissionStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Transmission status transition counter property", id: .init(level: 4, index: 6), name: "transmissionStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "External synchronization status property", id: .init(level: 4, index: 7), name: "externalSynchronizationStatus", typeName: "NcSynchronizationStatus", isReadOnly: true),
        .init(description: "External synchronization status message property", id: .init(level: 4, index: 8), name: "externalSynchronizationStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "External synchronization status transition counter property", id: .init(level: 4, index: 9), name: "externalSynchronizationStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "Synchronization source id property", id: .init(level: 4, index: 10), name: "synchronizationSourceId", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Essence status property", id: .init(level: 4, index: 11), name: "essenceStatus", typeName: "NcEssenceStatus", isReadOnly: true),
        .init(description: "Essence status message property", id: .init(level: 4, index: 12), name: "essenceStatusMessage", typeName: "NcString", isReadOnly: true, isNullable: true),
        .init(description: "Essence status transition counter property", id: .init(level: 4, index: 13), name: "essenceStatusTransitionCounter", typeName: "NcUint64", isReadOnly: true),
        .init(description: "Automatic reset counters and status messages property (default: true)", id: .init(level: 4, index: 14), name: "autoResetCountersAndMessages", typeName: "NcBoolean", isReadOnly: false),
      ],
      methods: [
        .init(description: "Gets the transmission error counters", id: .init(level: 4, index: 1), name: "GetTransmissionErrorCounters", resultDatatype: "NcMethodResultCounters", parameters: [
        ]),
        .init(description: "Resets ALL counters and status messages", id: .init(level: 4, index: 2), name: "ResetCountersAndMessages", resultDatatype: "NcMethodResult", parameters: [
        ]),
      ],
      events: [
      ]
    ),
  ]

  static let monitoringDatatypes: [NcDatatypeDescriptor] = [
    .init(description: "Connection status enum data type", name: "NcConnectionStatus", kind: .enum(items: [
      .init(description: "Inactive", name: "Inactive", value: 0),
      .init(description: "Active and healthy", name: "Healthy", value: 1),
      .init(description: "Active and partially healthy", name: "PartiallyHealthy", value: 2),
      .init(description: "Active and unhealthy", name: "Unhealthy", value: 3),
    ])),
    .init(description: "Counter data type", name: "NcCounter", kind: .struct(fields: [
      .init(description: "Counter name", name: "name", typeName: "NcString"),
      .init(description: "Counter value", name: "value", typeName: "NcUint64"),
      .init(description: "Optional counter description", name: "description", typeName: "NcString", isNullable: true),
    ], parentType: nil)),
    .init(description: "Essence status enum data type", name: "NcEssenceStatus", kind: .enum(items: [
      .init(description: "Inactive", name: "Inactive", value: 0),
      .init(description: "Active and healthy", name: "Healthy", value: 1),
      .init(description: "Active and partially healthy", name: "PartiallyHealthy", value: 2),
      .init(description: "Active and unhealthy", name: "Unhealthy", value: 3),
    ])),
    .init(description: "Link status enum data type", name: "NcLinkStatus", kind: .enum(items: [
      .init(description: "All the associated network interfaces are up", name: "AllUp", value: 1),
      .init(description: "Some of the associated network interfaces are down", name: "SomeDown", value: 2),
      .init(description: "All the associated network interfaces are down", name: "AllDown", value: 3),
    ])),
    .init(description: "Counters method result", name: "NcMethodResultCounters", kind: .struct(fields: [
      .init(description: "Counters", name: "value", typeName: "NcCounter", isSequence: true),
    ], parentType: "NcMethodResult")),
    .init(description: "Overall status enum data type", name: "NcOverallStatus", kind: .enum(items: [
      .init(description: "Inactive", name: "Inactive", value: 0),
      .init(description: "The overall status is healthy", name: "Healthy", value: 1),
      .init(description: "The overall status is partially healthy", name: "PartiallyHealthy", value: 2),
      .init(description: "The overall status is unhealthy", name: "Unhealthy", value: 3),
    ])),
    .init(description: "Stream status enum data type", name: "NcStreamStatus", kind: .enum(items: [
      .init(description: "Inactive", name: "Inactive", value: 0),
      .init(description: "Active and healthy", name: "Healthy", value: 1),
      .init(description: "Active and partially healthy", name: "PartiallyHealthy", value: 2),
      .init(description: "Active and unhealthy", name: "Unhealthy", value: 3),
    ])),
    .init(description: "Synchronization status enum data type", name: "NcSynchronizationStatus", kind: .enum(items: [
      .init(description: "Feature not in use", name: "NotUsed", value: 0),
      .init(description: "Locked to a synchronization source", name: "Healthy", value: 1),
      .init(description: "Partially locked to a synchronization source", name: "PartiallyHealthy", value: 2),
      .init(description: "Not locked to a synchronization source", name: "Unhealthy", value: 3),
    ])),
    .init(description: "Transmission status enum data type", name: "NcTransmissionStatus", kind: .enum(items: [
      .init(description: "Inactive", name: "Inactive", value: 0),
      .init(description: "Active and healthy", name: "Healthy", value: 1),
      .init(description: "Active and partially healthy", name: "PartiallyHealthy", value: 2),
      .init(description: "Active and unhealthy", name: "Unhealthy", value: 3),
    ])),
  ]
}
